# Generated by Django 4.1.1 on 2022-10-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.EmailField(primary_key=True,max_length=254)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('purchase_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
