# Generated by Django 4.1.1 on 2022-10-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_alter_bouquetinventory_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquetinventory',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
