# Generated by Django 4.1.2 on 2022-10-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_alter_bouquetinventory_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_notes',
            field=models.CharField(default=0.001483679525222552, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default=0.001483679525222552, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
